project:
  type: website
  output-dir: docs

website:
  title: "State of Working America Data Library"
  search: false
  navbar:
    background: light
    left:
      - text: What's New
        href: news.qmd

format:
  html:
    theme: cosmo
    toc: false
