project:
  type: website
  output-dir: docs

website:
  title: "State of Working America Data Library"
  search: false
  navbar:
    background: light
    left:
      - text: What's New
        href: news.qmd
  google-analytics: 
    tracking-id: "G-XE78VBJ0WK"

format:
  html:
    theme: cosmo
    toc: false
