project:
  type: website
  output-dir: docs

website:
  title: "State of Working America Data Library"
  search: false
  navbar:
    background: light
    left:
      - text: Available data
        href: available_data.qmd
      - text: Downloads
        href: downloads.qmd
      - text: What's New
        href: news.qmd
    right:
      - icon: github
        href: https://github.com/economic/dashboard_deploy_data
        aria-label: SWA Data Library GitHub  
format:
  html:
    theme: cosmo
    toc: false