---
title: Changelog
---

## Version 2025.11.13
* Update productivity pay quarterly measures to include 2025 Q2 data
* Update CEO pay data to include 2024 data

## Version 2025.9.15
* Add August 2025 data monthly measures in CPS based indicators and real monthly minimum wage data

## Version 2025.8.14
* Add July 2025 data monthly measures in CPS based indicators and real monthly minimum wage data

## Version 2025.7.17
* Add June 2025 data monthly measures in CPS based indicators and real monthly minimum wage data

## Version 2025.6.18
* Add May 2025 data for monthly measures in CPS based indicators and real monthly minimum wage data

## Version 2025.5.23
* Add 2025Q1 productivity/pay quarterly data
* Add race X education and race X age group dimensions for wage values in average wages, median wages, and wage percentiles 

## Version 2025.5.14
* Add April 2025 data for monthly measures in CPS based indicators
* Add April 2025 data for real monthly minimum wage data with April 2025 CPI update

## Version 2025.4.16
* Include two new indicators, Working age population, and Economically insecure population
* META: Change versioning convention from semantic versioning to calendar versioning
* Add data for March 2025 for monthly measures in CPS based indicators
* Update productivity Pay data through 2024Q4 (see https://www.epi.org/productivity-pay-gap/ for more)
* Added more focus options for wage and employment indicators (gender by education, education by age group, and age group by gender)

## Version 1.0.2
* Adds data for January and February 2025 for monthly measures in CPS based indicators where available
* Changes methodology for calculating wage percentiles and median wages, now using a [smoothed quantile](https://economic.github.io/epidatatools/reference/averaged_quantile.html) method
* Suppresses wage percentile values if the share of topcoded individuals near a given percentile value is higher than a 10% threshold. See [here](https://www.epi.org/blog/stagnant-topcode-thresholds-threaten-data-reliability-for-the-highest-earners-and-make-inequality-difficult-to-accurately-measure/), and [here](https://microdata.epi.org/methodology/wagevariables/#top-code-adjustments) for more details. 

## Version 1.0.1
* Fix college wage premium indicator, previously was showing up as a negative value

## Version 1.0.0
* Full public release
* Adds 2024 data for CPS based indicators

## Version 0.0.9000
* Preparing soft launch release